/**
 * Build-time SVG transform.
 *
 * Reads the source logo from `docs/app_daddy_logo.svg`, strips the baked
 * background rect, and emits a transparent React component at
 * `components/brand/LogoMark.tsx`.
 *
 * Runs via `bun run prepare-logo` or automatically before `next build` via
 * the `prebuild` hook in `package.json`.
 *
 * Idempotent.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";

const SOURCE_SVG = resolve(process.cwd(), "docs/app_daddy_logo.svg");
const OUTPUT_TSX = resolve(process.cwd(), "components/brand/LogoMark.tsx");

const BACKGROUND_FILL = "#F3F0EE";

function stripBackgroundRect(svg: string): string {
  // Match the <rect> element whose fill equals the baked background color.
  const pattern = new RegExp(
    `<rect[^>]*?fill="${BACKGROUND_FILL}"[^>]*/?>`,
    "i",
  );
  const match = svg.match(pattern);

  if (!match) {
    throw new Error(
      `prepare-logo: no <rect fill="${BACKGROUND_FILL}"/> found in source SVG. ` +
        `The logo may have changed — inspect ${SOURCE_SVG} manually.`,
    );
  }

  return svg.replace(pattern, "");
}

function toReactComponent(svg: string): string {
  const openTag = svg.match(/<svg[^>]*>/);
  if (!openTag) {
    throw new Error("prepare-logo: malformed SVG — no opening <svg> tag.");
  }

  const body = svg
    .replace(/<\?xml[^?]*\?>/gi, "")
    .replace(openTag[0], "")
    .replace(/<\/svg>\s*$/i, "")
    .trim();

  const viewBox = "0 0 260 188";

  const header =
    "// AUTO-GENERATED by scripts/prepare-logo.ts — do not edit by hand.\n" +
    "// Run `bun run prepare-logo` to regenerate from docs/app_daddy_logo.svg.\n\n" +
    'import type { SVGProps } from "react";\n\n' +
    "export function LogoMark(props: SVGProps<SVGSVGElement>) {\n" +
    "  return (\n" +
    `    <svg\n` +
    `      xmlns="http://www.w3.org/2000/svg"\n` +
    `      viewBox="${viewBox}"\n` +
    `      aria-hidden="true"\n` +
    `      {...props}\n` +
    `    >`;

  const footer = "</svg>\n  );\n}\n";

  return `${header}${body}${footer}`;
}

function main(): void {
  if (!existsSync(SOURCE_SVG)) {
    throw new Error(`prepare-logo: source SVG not found at ${SOURCE_SVG}`);
  }

  const source = readFileSync(SOURCE_SVG, "utf8");
  const transparent = stripBackgroundRect(source);
  const component = toReactComponent(transparent);

  const outDir = dirname(OUTPUT_TSX);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  writeFileSync(OUTPUT_TSX, component, "utf8");

  const bytesIn = Buffer.byteLength(source, "utf8");
  const bytesOut = Buffer.byteLength(component, "utf8");
  console.log(
    `prepare-logo: wrote ${OUTPUT_TSX} (${bytesIn} → ${bytesOut} bytes)`,
  );
}

main();
