/**
 * Build-time SVG transform.
 *
 * Reads the source logo from `docs/app_daddy_logo.svg` and emits a React
 * component wrapping the markup at `components/brand/LogoMark.tsx`.
 *
 * Runs via `bun run prepare-logo` or automatically before `next build` via
 * the `prebuild` hook in `package.json`.
 *
 * ----------------------------------------------------------------------
 * TEMPORARY (2026-04-07): Background rect strip is disabled.
 *
 * The source SVG is raster-traced: its "dark" letterforms are charcoal
 * paths (~#181C1F — #222728) authored to be viewed on the baked-in
 * `#F5F4F1` cream background. Stripping the background leaves those paths
 * floating alone, and on dark mode they become charcoal-on-charcoal —
 * invisible.
 *
 * Until a proper vector-authored logo exists, we ship the SVG as-is
 * (including its baked cream rect) and match the page background to it
 * in `app/globals.css`. To revert: re-enable `stripBackgroundRect(source)`
 * in main() below and remove the `--background` override in globals.css.
 * ----------------------------------------------------------------------
 *
 * Idempotent.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";

const SOURCE_SVG = resolve(process.cwd(), "docs/app_daddy_logo.svg");
const OUTPUT_TSX = resolve(process.cwd(), "components/brand/LogoMark.tsx");

const BACKGROUND_FILL = "#F5F4F1";

// TEMPORARY: Disabled — see file header. Kept here so re-enabling is a
// one-line change in main() once a real vector logo arrives.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function stripBackgroundRect(svg: string): string {
  // Match the first <path> element whose fill attribute equals #F5F4F1.
  // The raster-traced logo has exactly one such path (the canvas background);
  // every other path is a chromatic detail on the mark itself.
  const pattern = new RegExp(
    `<path[^>]*?fill="${BACKGROUND_FILL}"[^>]*?/>`,
    "i",
  );
  const match = svg.match(pattern);

  if (!match) {
    throw new Error(
      `prepare-logo: no <path fill="${BACKGROUND_FILL}"/> found in source SVG. ` +
        `The logo may have been replaced — inspect ${SOURCE_SVG} manually.`,
    );
  }

  return svg.replace(pattern, "");
}

function toReactComponent(svg: string): string {
  // Convert <svg ...> opening tag to accept React SVGProps spread.
  // The raw SVG includes attributes like version, xmlns, width, height that
  // we preserve, but we also need to inject {...props} so callers can pass
  // className, aria-*, etc.
  const openTag = svg.match(/<svg[^>]*>/);
  if (!openTag) {
    throw new Error("prepare-logo: malformed SVG — no opening <svg> tag.");
  }

  const body = svg
    .replace(/<\?xml[^?]*\?>/gi, "")
    .replace(openTag[0], "")
    .replace(/<\/svg>\s*$/i, "")
    .trim();

  // Rebuild the opening tag for JSX: keep xmlns and viewBox, drop the
  // XML declaration and version attribute. Use viewBox so callers control
  // the size via className (not fixed width/height).
  const viewBox = "0 0 2130 1984";

  const header =
    "// AUTO-GENERATED by scripts/prepare-logo.ts — do not edit by hand.\n" +
    "// Run `bun run prepare-logo` to regenerate from docs/app_daddy_logo.svg.\n\n" +
    'import type { SVGProps } from "react";\n\n' +
    "export function LogoMark(props: SVGProps<SVGSVGElement>) {\n" +
    "  return (\n" +
    `    <svg\n` +
    `      xmlns="http://www.w3.org/2000/svg"\n` +
    `      viewBox="${viewBox}"\n` +
    `      aria-hidden="true"\n` +
    `      {...props}\n` +
    `    >`;

  const footer = "</svg>\n  );\n}\n";

  return `${header}${body}${footer}`;
}

function main(): void {
  if (!existsSync(SOURCE_SVG)) {
    throw new Error(`prepare-logo: source SVG not found at ${SOURCE_SVG}`);
  }

  const source = readFileSync(SOURCE_SVG, "utf8");
  // TEMPORARY: ship the SVG as-is, including its baked cream background.
  // Re-enable the line below when a proper vector logo replaces the trace.
  // const transparent = stripBackgroundRect(source);
  const component = toReactComponent(source);

  const outDir = dirname(OUTPUT_TSX);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  writeFileSync(OUTPUT_TSX, component, "utf8");

  const bytesIn = Buffer.byteLength(source, "utf8");
  const bytesOut = Buffer.byteLength(component, "utf8");
  console.log(
    `prepare-logo: wrote ${OUTPUT_TSX} (${bytesIn} → ${bytesOut} bytes)`,
  );
}

main();
