/**
 * Pure SVG → React component transform.
 *
 * Extracted from the build CLI (`scripts/prepare-logo.ts`) so the transform
 * can be unit-tested in isolation, with no filesystem side effects on import.
 *
 * Deterministic: the same input string always produces byte-identical output.
 */

/** viewBox baked into the emitted component (matches the source artwork). */
export const VIEW_BOX = "0 0 260 188";

/**
 * Converts a raw SVG string into the source of an `<LogoMark />` React
 * component: strips the XML declaration and the source `<svg>` wrapper, then
 * re-wraps the inner markup in a typed, prop-spreading component.
 *
 * @throws if the input has no opening `<svg>` tag (malformed source).
 */
export function toReactComponent(svg: string): string {
  const openTag = svg.match(/<svg[^>]*>/);
  if (!openTag) {
    throw new Error("prepare-logo: malformed SVG — no opening <svg> tag.");
  }

  const body = svg
    .replace(/<\?xml[^?]*\?>/gi, "")
    .replace(openTag[0], "")
    .replace(/<\/svg>\s*$/i, "")
    .trim();

  const header =
    "// AUTO-GENERATED by scripts/prepare-logo.ts — do not edit by hand.\n" +
    "// Run `bun run prepare-logo` to regenerate from docs/app_daddy_logo.svg.\n\n" +
    'import type { SVGProps } from "react";\n\n' +
    "export function LogoMark(props: SVGProps<SVGSVGElement>) {\n" +
    "  return (\n" +
    `    <svg\n` +
    `      xmlns="http://www.w3.org/2000/svg"\n` +
    `      viewBox="${VIEW_BOX}"\n` +
    `      aria-hidden="true"\n` +
    `      {...props}\n` +
    `    >`;

  const footer = "</svg>\n  );\n}\n";

  return `${header}${body}${footer}`;
}
